[build]
rustflags = [
    "-C", "target-feature=-crt-static",
    "-C", "link-arg=/DELAYLOAD:cublas64_13.dll",
    "-C", "link-arg=/DELAYLOAD:cublasLt64_13.dll",
    "-C", "link-arg=/DELAYLOAD:cudart64_13.dll",
    "-C", "link-arg=/DELAYLOAD:cudnn64_9.dll",
    "-C", "link-arg=/DELAYLOAD:cudnn_engines_precompiled64_9.dll",
    "-C", "link-arg=/DELAYLOAD:onnxruntime_providers_cuda.dll",
    "-C", "link-arg=delayimp.lib"
]

[env]
CMAKE_GENERATOR = { value = "Ninja", force = true }
CMAKE_MAKE_PROGRAM = { value = "C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe", force = true }
